export const GET_ASSIGNMENTS = 'GET_ASSIGNMENTS';
export const ADD_ASSIGNMENT = 'ADD_ASSIGNMENT';
export const DELETE_ASSIGNMENT = 'DELETE_ASSIGNMENT';
export const CLEAR_ASSIGNMENTS = 'CLEAR_ASSIGNMENTS';
